[package]
name = "mimir"
version = "1.0.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
float-cmp = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
symbol = "0.1.9"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "criterion_evaluate"
harness = false